import { SafeAreaTopScrim } from "./SafeArea";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api, type ApiResponse } from "./api";

type AppState = ApiResponse<typeof api, "getState">;
type Product = AppState["products"][number];
type Sale = AppState["sales"][number];
type Debt = AppState["debts"][number];
type Tab = "home" | "sales" | "products" | "finance" | "more";
type Modal = "product" | "expense" | "shop" | "member" | null;
type Lang = "fr" | "rn";

const words = {
  fr: { home: "Accueil", sales: "Ventes", products: "Produits", finance: "Finances", more: "Plus", today: "Aujourd’hui", revenue: "Chiffre d’affaires", profit: "Bénéfice estimé", expenses: "Dépenses", salesCount: "Ventes", stockAlert: "Stock à surveiller", newSale: "Nouvelle vente", cart: "Panier", total: "Total", save: "Enregistrer", cancel: "Annuler", search: "Rechercher un produit", report: "Rapport", debts: "Dettes clients", add: "Ajouter", logout: "Se déconnecter" },
  rn: { home: "Ahabanza", sales: "Ivyagurishijwe", products: "Ibicuruzwa", finance: "Amafaranga", more: "Ibindi", today: "Uno musi", revenue: "Amafaranga yinjiye", profit: "Inyungu yagereranijwe", expenses: "Amafaranga yasohotse", salesCount: "Ivyagurishijwe", stockAlert: "Ibisigaye bike", newSale: "Gurisha", cart: "Agatebo", total: "Igiteranyo", save: "Bika", cancel: "Hagarika", search: "Rondera igicuruzwa", report: "Raporo", debts: "Amadeni y’abaguzi", add: "Ongerako", logout: "Sohoka" },
} satisfies Record<Lang, Record<string, string>>;

const money = new Intl.NumberFormat("fr-BI", { style: "currency", currency: "BIF", maximumFractionDigits: 0 });
const formatMoney = (value: number) => money.format(value).replace("BIF", "BIF");
const dateTime = (value: number) => new Intl.DateTimeFormat("fr-BI", { dateStyle: "medium", timeStyle: "short" }).format(value);
const dayKey = (value: number) => { const d = new Date(value); return `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`; };
const startOfDay = (d = new Date()) => new Date(d.getFullYear(), d.getMonth(), d.getDate()).getTime();
const friendlyError = (error: unknown) => { const value = String(error instanceof Error ? error.message : error); const match = value.match(/(?:Error: )?([^\n]+)$/); return match?.[1] ?? "Une erreur est survenue."; };

function Icon({ name }: { name: "home" | "sale" | "box" | "wallet" | "more" | "plus" | "search" | "alert" | "store" | "user" | "download" }) {
  const paths: Record<string, ReactNode> = {
    home: <><path d="M3 10.5 12 3l9 7.5"/><path d="M5 9.5V21h14V9.5M9 21v-7h6v7"/></>,
    sale: <><path d="M6 2h12l1 20-7-3-7 3L6 2Z"/><path d="M9 7h6M9 11h6"/></>,
    box: <><path d="m4 7 8-4 8 4-8 4-8-4Z"/><path d="m4 7 8 4 8-4v10l-8 4-8-4V7Z"/><path d="M12 11v10"/></>,
    wallet: <><path d="M3 6h17v14H3z"/><path d="M16 10h5v6h-5a3 3 0 0 1 0-6Z"/><path d="M3 6l13-3v3"/></>,
    more: <><circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/></>,
    plus: <><path d="M12 5v14M5 12h14"/></>, search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, alert: <><path d="M12 3 2 21h20L12 3Z"/><path d="M12 9v5M12 18h.01"/></>, store: <><path d="M3 9h18l-2-5H5L3 9Z"/><path d="M5 9v11h14V9M9 20v-6h6v6"/></>, user: <><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>, download: <><path d="M12 3v12m0 0 5-5m-5 5-5-5"/><path d="M5 21h14"/></>,
  };
  return <svg aria-hidden="true" viewBox="0 0 24 24" className="icon" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
function Sheet({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="sheet-backdrop" role="presentation" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><section className="sheet" role="dialog" aria-modal="true" aria-label={title}><div className="sheet-head"><h2>{title}</h2><button className="text-btn" onClick={onClose}>Fermer</button></div>{children}</section></div>; }
function Empty({ title, body }: { title: string; body: string }) { return <div className="empty"><div className="empty-mark">—</div><strong>{title}</strong><p>{body}</p></div>; }
function Notice({ text, tone = "info" }: { text: string; tone?: "info" | "error" | "success" }) { return <div className={`notice ${tone}`} role="status">{text}</div>; }

function AuthScreen({ onAuth }: { onAuth: (token: string, shopId: number) => void }) {
  const [mode, setMode] = useState<"create" | "login">("create");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [demo, setDemo] = useState(true);
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); setError(""); setBusy(true); const data = new FormData(e.currentTarget);
    try {
      const result = mode === "create" ? await api.createAccount({ name: String(data.get("name") ?? ""), email: String(data.get("email") ?? ""), password: String(data.get("password") ?? ""), shopName: String(data.get("shop") ?? ""), includeDemo: demo }) : await api.login({ email: String(data.get("email") ?? ""), password: String(data.get("password") ?? "") });
      onAuth(result.token, result.shopId);
    } catch (err) { setError(friendlyError(err)); } finally { setBusy(false); }
  }
  return <main className="auth-shell"><section className="auth-copy"><h1 className="auth-brand"><span className="auth-brand-main">BIZTRACK</span><span className="auth-brand-place">BURUNDI</span></h1><p className="kicker">Caisse • stock • bénéfice</p><p className="auth-tagline">Votre commerce,<br/>dans votre poche.</p><p>Une caisse simple en francs burundais, pensée pour le rythme du comptoir.</p><div className="auth-proof"><span>Ventes rapides</span><span>Stocks précis</span><span>Rapports utiles</span></div></section><section className="auth-panel"><div className="segmented"><button className={mode === "create" ? "active" : ""} onClick={() => setMode("create")}>Créer un compte</button><button className={mode === "login" ? "active" : ""} onClick={() => setMode("login")}>Connexion</button></div><form onSubmit={submit} className="stack-form">{mode === "create" && <><Field label="Votre nom"><input name="name" required minLength={2} autoComplete="name" /></Field><Field label="Nom de la boutique"><input name="shop" required minLength={2} /></Field></>}<Field label="Adresse e-mail"><input name="email" type="email" required autoComplete="email" /></Field><Field label="Mot de passe"><input name="password" type="password" required minLength={mode === "create" ? 6 : 1} autoComplete={mode === "create" ? "new-password" : "current-password"} /></Field>{mode === "create" && <label className="check"><input type="checkbox" checked={demo} onChange={(e) => setDemo(e.target.checked)} /><span>Ajouter quelques produits de démonstration modifiables</span></label>}{error && <Notice text={error} tone="error"/>}<button className="primary" disabled={busy}>{busy ? "Patientez…" : mode === "create" ? "Ouvrir ma boutique" : "Se connecter"}</button></form><p className="fineprint">Compte local à cet espace. Vos données sont séparées par boutique.</p></section></main>;
}

export function App() {
  const qc = useQueryClient();
  const [token, setToken] = useState(() => localStorage.getItem("biztrack_token") ?? "");
  const [shopId, setShopId] = useState(() => Number(localStorage.getItem("biztrack_shop")) || undefined);
  const [tab, setTab] = useState<Tab>("home");
  const [modal, setModal] = useState<Modal>(null);
  const [lang, setLang] = useState<Lang>(() => (localStorage.getItem("biztrack_lang") === "rn" ? "rn" : "fr"));
  const [editing, setEditing] = useState<Product | null>(null);
  const [cart, setCart] = useState<Record<number, number>>({});
  const [search, setSearch] = useState("");
  const [payment, setPayment] = useState<"cash" | "lumicash" | "ecocash" | "credit">("cash");
  const [customer, setCustomer] = useState("");
  const [receipt, setReceipt] = useState<Sale | null>(null);
  const [period, setPeriod] = useState<"day" | "week" | "month">("day");
  const [toast, setToast] = useState("");
  const t = words[lang];

  const cacheKey = token && shopId ? `biztrack_cache_${token.slice(0, 8)}_${shopId}` : "";
  const stateQuery = useQuery({ queryKey: ["state", token, shopId], queryFn: () => api.getState({ token, shopId }), enabled: Boolean(token), retry: 1 });
  const cached = useMemo<AppState | null>(() => { if (!cacheKey) return null; try { return JSON.parse(localStorage.getItem(cacheKey) ?? "null") as AppState | null; } catch { return null; } }, [cacheKey, stateQuery.dataUpdatedAt]);
  const state = stateQuery.data ?? cached;
  const offline = Boolean(token && !stateQuery.data && cached);

  useEffect(() => { if (stateQuery.data && cacheKey) localStorage.setItem(cacheKey, JSON.stringify(stateQuery.data)); }, [stateQuery.data, cacheKey]);
  useEffect(() => { localStorage.setItem("biztrack_lang", lang); }, [lang]);
  useEffect(() => { if (toast) { const id = setTimeout(() => setToast(""), 3200); return () => clearTimeout(id); } }, [toast]);

  function authenticated(nextToken: string, nextShop: number) { localStorage.setItem("biztrack_token", nextToken); localStorage.setItem("biztrack_shop", String(nextShop)); setToken(nextToken); setShopId(nextShop); }
  async function refresh() { await qc.invalidateQueries({ queryKey: ["state"] }); }
  function selectShop(id: number) { localStorage.setItem("biztrack_shop", String(id)); setShopId(id); setTab("home"); }
  async function logout() { try { await api.logout({ token }); } catch { /* local logout still works */ } localStorage.removeItem("biztrack_token"); localStorage.removeItem("biztrack_shop"); setToken(""); setShopId(undefined); qc.clear(); }

  if (!token) return <><SafeAreaTopScrim backgroundColor="var(--bg)"/><AuthScreen onAuth={authenticated}/></>;
  if (stateQuery.isPending && !state) return <main className="loading"><div className="spinner"/><p>Ouverture de la boutique…</p></main>;
  if (!state) return <main className="loading"><Notice text={friendlyError(stateQuery.error)} tone="error"/><button className="primary" onClick={() => void stateQuery.refetch()}>Réessayer</button><button className="text-btn" onClick={() => void logout()}>Se déconnecter</button></main>;

  const activeShopId = state.activeShopId;
  const activeShop = state.shops.find((s) => s.id === activeShopId) ?? state.shops[0];
  const role = activeShop?.role ?? "cashier";
  const canManage = role === "owner" || role === "manager";
  const canDelete = role === "owner";
  const todayStart = startOfDay();
  const todaySales = state.sales.filter((s) => s.createdAt >= todayStart);
  const todayExpenses = state.expenses.filter((e) => e.createdAt >= todayStart);
  const revenueToday = todaySales.reduce((sum, s) => sum + s.total, 0);
  const expensesToday = todayExpenses.reduce((sum, e) => sum + e.amount, 0);
  const profitToday = todaySales.reduce((sum, s) => sum + s.total - s.costTotal, 0) - expensesToday;
  const alerts = state.products.filter((p) => p.stock <= p.lowStockThreshold);
  const chartData = Array.from({ length: 7 }, (_, index) => { const d = new Date(); d.setHours(0, 0, 0, 0); d.setDate(d.getDate() - (6 - index)); const key = dayKey(d.getTime()); return { day: new Intl.DateTimeFormat(lang === "rn" ? "rn-BI" : "fr-BI", { weekday: "short" }).format(d), ventes: state.sales.filter((s) => dayKey(s.createdAt) === key).reduce((sum, s) => sum + s.total, 0) }; });

  const periodStart = (() => { const now = new Date(); if (period === "day") return startOfDay(now); if (period === "week") { const d = new Date(now.getFullYear(), now.getMonth(), now.getDate()); const weekday = (d.getDay() + 6) % 7; d.setDate(d.getDate() - weekday); return d.getTime(); } return new Date(now.getFullYear(), now.getMonth(), 1).getTime(); })();
  const periodSales = state.sales.filter((s) => s.createdAt >= periodStart);
  const periodExpenses = state.expenses.filter((e) => e.createdAt >= periodStart);
  const reportRevenue = periodSales.reduce((sum, s) => sum + s.total, 0);
  const reportMargin = periodSales.reduce((sum, s) => sum + s.total - s.costTotal, 0);
  const reportExpenses = periodExpenses.reduce((sum, e) => sum + e.amount, 0);

  async function mutate<T>(work: () => Promise<T>, success: string) { if (offline || !navigator.onLine) { setToast("Connexion requise pour enregistrer. Vos données consultées restent disponibles hors ligne."); return null; } try { const result = await work(); await refresh(); setToast(success); return result; } catch (err) { setToast(friendlyError(err)); return null; } }

  function addToCart(product: Product) { if (product.stock < 1) return; setCart((current) => ({ ...current, [product.id]: Math.min(product.stock, (current[product.id] ?? 0) + 1) })); }
  const cartLines = Object.entries(cart).map(([id, quantity]) => ({ product: state.products.find((p) => p.id === Number(id)), quantity })).filter((line): line is { product: Product; quantity: number } => Boolean(line.product && line.quantity > 0));
  const cartTotal = cartLines.reduce((sum, line) => sum + line.product.salePrice * line.quantity, 0);

  async function saveSale() { const result = await mutate(() => api.createSale({ token, shopId: activeShopId, paymentMethod: payment, customerName: customer || undefined, items: cartLines.map((line) => ({ productId: line.product.id, quantity: line.quantity })) }), "Vente enregistrée"); if (result) { const nowSale: Sale = { id: result.id, total: result.total, costTotal: cartLines.reduce((s, l) => s + l.product.purchasePrice * l.quantity, 0), paymentMethod: payment, customerName: customer || null, createdAt: Date.now(), items: cartLines.map((l, index) => ({ id: -index - 1, productId: l.product.id, productName: l.product.name, quantity: l.quantity, unitPrice: l.product.salePrice, unitCost: l.product.purchasePrice })) }; setReceipt(nowSale); setCart({}); setCustomer(""); } }

  async function shareReceipt(sale: Sale) { const shopName = activeShop?.name ?? "Boutique"; const lines = [`${shopName}`, `Reçu N° ${sale.id}`, dateTime(sale.createdAt), "", ...sale.items.map((i) => `${i.quantity} × ${i.productName} — ${formatMoney(i.quantity * i.unitPrice)}`), "", `TOTAL : ${formatMoney(sale.total)}`, `Paiement : ${sale.paymentMethod}`]; const text = lines.join("\n"); if (navigator.share) { try { await navigator.share({ title: `Reçu ${sale.id}`, text }); return; } catch { /* download fallback */ } } const blob = new Blob([text], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `recu-${sale.id}.txt`; a.click(); URL.revokeObjectURL(url); }

  function exportReport() { const rows = [["Type", "Date", "Libellé", "Mode", "Montant BIF"], ...periodSales.map((s) => ["Vente", new Date(s.createdAt).toISOString(), `Vente ${s.id}`, s.paymentMethod, String(s.total)]), ...periodExpenses.map((e) => ["Dépense", new Date(e.createdAt).toISOString(), e.label, "", String(-e.amount)])]; const csv = rows.map((r) => r.map((v) => `"${String(v).replaceAll('"', '""')}"`).join(";")).join("\n"); const blob = new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `rapport-${period}.csv`; a.click(); URL.revokeObjectURL(url); }

  const filteredProducts = state.products.filter((p) => p.name.toLowerCase().includes(search.toLowerCase()));

  return <div className="app-shell"><SafeAreaTopScrim backgroundColor="var(--bg)"/>{offline && <div className="offline">Mode hors ligne • dernière sauvegarde {new Intl.DateTimeFormat("fr-BI", { timeStyle: "short" }).format(state.syncedAt)}</div>}<header className="topbar"><div><span className="top-label">{activeShop?.name}</span><strong>{tab === "home" ? t.today : tab === "sales" ? t.sales : tab === "products" ? t.products : tab === "finance" ? t.finance : t.more}</strong></div><button className="shop-chip" onClick={() => setTab("more")} aria-label="Changer de boutique"><Icon name="store"/><span>{role === "owner" ? "Propriétaire" : role === "manager" ? "Gérant" : "Caissier"}</span></button></header><main className="content">
    {tab === "home" && <section className="dashboard"><div className="hero-ledger"><div className="hero-main"><span>{t.revenue}</span><strong>{formatMoney(revenueToday)}</strong><small>{todaySales.length} transaction{todaySales.length !== 1 ? "s" : ""}</small></div><div className="hero-side"><div><span>{t.profit}</span><b className={profitToday < 0 ? "negative" : ""}>{formatMoney(profitToday)}</b></div><div><span>{t.expenses}</span><b>{formatMoney(expensesToday)}</b></div></div></div><button className="quick-sale" onClick={() => setTab("sales")}><Icon name="plus"/><span>{t.newSale}</span><small>Encaisser en quelques secondes</small></button><div className="section-head"><h2>Ventes sur 7 jours</h2><span>BIF</span></div><div className="chart-wrap" aria-label="Graphique des ventes sur sept jours"><ResponsiveContainer width="100%" height={210}><AreaChart data={chartData} margin={{ top: 12, right: 8, left: -12, bottom: 0 }}><defs><linearGradient id="salesFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--accent)" stopOpacity={0.32}/><stop offset="1" stopColor="var(--accent)" stopOpacity={0.03}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: "var(--dim)", fontSize: 12 }}/><YAxis domain={[0, "auto"]} axisLine={false} tickLine={false} tick={{ fill: "var(--dim)", fontSize: 11 }} tickFormatter={(v: number) => v >= 1000 ? `${Math.round(v / 1000)}k` : String(v)}/><Tooltip formatter={(v: number) => [formatMoney(v), "Ventes"]} contentStyle={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 10 }}/><Area type="monotone" dataKey="ventes" stroke="var(--accent)" strokeWidth={3} fill="url(#salesFill)"/></AreaChart></ResponsiveContainer></div><div className="section-head"><h2>{t.stockAlert}</h2><span>{alerts.length}</span></div>{alerts.length ? <div className="stock-list">{alerts.slice(0, 5).map((p) => <button key={p.id} onClick={() => { setEditing(p); setModal("product"); }}><span className={p.stock === 0 ? "stock-dot out" : "stock-dot"}/><span><b>{p.name}</b><small>{p.stock === 0 ? "Rupture de stock" : `${p.stock} restant${p.stock > 1 ? "s" : ""}`}</small></span><strong>{formatMoney(p.salePrice)}</strong></button>)}</div> : <Empty title="Stock en ordre" body="Aucun produit n’a atteint son seuil d’alerte."/>}</section>}

    {tab === "sales" && <section><div className="search-row"><Icon name="search"/><input aria-label={t.search} placeholder={t.search} value={search} onChange={(e) => setSearch(e.target.value)}/></div><div className="sales-layout"><div><div className="product-pick">{filteredProducts.map((p) => <button key={p.id} disabled={p.stock === 0} onClick={() => addToCart(p)}><span><b>{p.name}</b><small>{p.stock} en stock</small></span><strong>{formatMoney(p.salePrice)}</strong><span className="add-circle"><Icon name="plus"/></span></button>)}{!filteredProducts.length && <Empty title="Aucun produit" body="Modifiez votre recherche ou ajoutez un produit."/>}</div><div className="section-head history-head"><h2>Historique</h2><span>{state.sales.length}</span></div><div className="history-list">{state.sales.slice(0, 25).map((s) => <button key={s.id} onClick={() => setReceipt(s)}><span><b>Vente N° {s.id}</b><small>{dateTime(s.createdAt)} • {s.paymentMethod}</small></span><strong>{formatMoney(s.total)}</strong></button>)}</div></div><aside className="cart-panel"><div className="section-head"><h2>{t.cart}</h2><span>{cartLines.reduce((s, l) => s + l.quantity, 0)}</span></div>{cartLines.length ? <>{cartLines.map((line) => <div className="cart-line" key={line.product.id}><div><b>{line.product.name}</b><small>{formatMoney(line.product.salePrice)}</small></div><div className="stepper"><button aria-label={`Réduire ${line.product.name}`} onClick={() => setCart((c) => ({ ...c, [line.product.id]: Math.max(0, line.quantity - 1) }))}>−</button><span>{line.quantity}</span><button aria-label={`Augmenter ${line.product.name}`} onClick={() => setCart((c) => ({ ...c, [line.product.id]: Math.min(line.product.stock, line.quantity + 1) }))}>+</button></div></div>)}<Field label="Mode de paiement"><select value={payment} onChange={(e) => setPayment(e.target.value as typeof payment)}><option value="cash">Cash</option><option value="lumicash">Lumicash</option><option value="ecocash">EcoCash</option><option value="credit">Crédit</option></select></Field>{payment === "credit" && <Field label="Nom du client"><input value={customer} onChange={(e) => setCustomer(e.target.value)} required /></Field>}<div className="cart-total"><span>{t.total}</span><strong>{formatMoney(cartTotal)}</strong></div><button className="primary" disabled={!cartLines.length || (payment === "credit" && !customer.trim())} onClick={() => void saveSale()}>{t.save} la vente</button></> : <Empty title="Panier vide" body="Touchez un produit pour commencer la vente."/>}</aside></div></section>}

    {tab === "products" && <section><div className="action-head"><div className="search-row"><Icon name="search"/><input aria-label={t.search} placeholder={t.search} value={search} onChange={(e) => setSearch(e.target.value)}/></div>{canManage && <button className="primary compact" onClick={() => { setEditing(null); setModal("product"); }}><Icon name="plus"/>Ajouter</button>}</div><div className="product-table"><div className="table-head"><span>Produit</span><span>Prix</span><span>Stock</span></div>{filteredProducts.map((p) => <button key={p.id} onClick={() => { setEditing(p); setModal("product"); }}><span><b>{p.name}</b><small>Marge {formatMoney(p.salePrice - p.purchasePrice)}</small></span><span>{formatMoney(p.salePrice)}</span><span className={p.stock <= p.lowStockThreshold ? "low" : ""}>{p.stock}</span></button>)}</div>{!filteredProducts.length && <Empty title="Aucun produit" body="Ajoutez votre premier article pour commencer."/>}</section>}

    {tab === "finance" && <section><div className="report-toolbar"><div className="segmented"><button className={period === "day" ? "active" : ""} onClick={() => setPeriod("day")}>Jour</button><button className={period === "week" ? "active" : ""} onClick={() => setPeriod("week")}>Semaine</button><button className={period === "month" ? "active" : ""} onClick={() => setPeriod("month")}>Mois</button></div><button className="secondary" onClick={exportReport}><Icon name="download"/>Excel / CSV</button></div><div className="finance-strip"><div><span>Recettes</span><strong>{formatMoney(reportRevenue)}</strong></div><div><span>Dépenses</span><strong>{formatMoney(reportExpenses)}</strong></div><div><span>Bénéfice net</span><strong className={reportMargin - reportExpenses < 0 ? "negative" : ""}>{formatMoney(reportMargin - reportExpenses)}</strong></div></div><div className="two-columns"><div><div className="section-head"><h2>Dépenses</h2>{canManage && <button className="text-btn" onClick={() => setModal("expense")}>+ Ajouter</button>}</div>{periodExpenses.length ? <div className="finance-list">{periodExpenses.map((e) => <div key={e.id}><span><b>{e.label}</b><small>{dateTime(e.createdAt)}{e.note ? ` • ${e.note}` : ""}</small></span><strong>−{formatMoney(e.amount)}</strong></div>)}</div> : <Empty title="Aucune dépense" body="Les dépenses de la période apparaîtront ici."/>}</div><div><div className="section-head"><h2>{t.debts}</h2><span>{state.debts.filter((d) => d.status === "open").length}</span></div>{state.debts.length ? <div className="debt-list">{state.debts.map((d) => <DebtRow key={d.id} debt={d} canManage={canManage} onPay={(amount) => void mutate(() => api.addDebtPayment({ token, shopId: state.activeShopId, debtId: d.id, amount }), "Paiement enregistré")}/>)}</div> : <Empty title="Aucune dette" body="Les ventes à crédit créent automatiquement une dette client."/>}</div></div></section>}

    {tab === "more" && <section className="settings"><div className="settings-block"><div className="section-head"><h2>Boutiques</h2><button className="text-btn" onClick={() => setModal("shop")}>+ Nouvelle</button></div>{state.shops.map((s) => <button className={`shop-row ${s.id === state.activeShopId ? "selected" : ""}`} key={s.id} onClick={() => selectShop(s.id)}><Icon name="store"/><span><b>{s.name}</b><small>{s.role === "owner" ? "Propriétaire" : s.role === "manager" ? "Gérant" : "Caissier"}</small></span>{s.id === state.activeShopId && <span className="selected-mark">Active</span>}</button>)}</div><div className="settings-block"><div className="section-head"><h2>Équipe</h2>{role === "owner" && <button className="text-btn" onClick={() => setModal("member")}>+ Membre</button>}</div>{state.members.map((m) => <div className="member-row" key={m.id}><Icon name="user"/><span><b>{m.name}</b><small>{m.email}</small></span><span className="role-tag">{m.role === "owner" ? "Propriétaire" : m.role === "manager" ? "Gérant" : "Caissier"}</span></div>)}</div><div className="settings-block"><div className="section-head"><h2>Langue</h2></div><div className="segmented"><button className={lang === "fr" ? "active" : ""} onClick={() => setLang("fr")}>Français</button><button className={lang === "rn" ? "active" : ""} onClick={() => setLang("rn")}>Kirundi</button></div></div><div className="account-row"><div><b>{state.account.name}</b><small>{state.account.email}</small></div><button className="danger-text" onClick={() => void logout()}>{t.logout}</button></div></section>}
  </main><nav className="bottom-nav" aria-label="Navigation principale">{([['home','home',t.home],['sales','sale',t.sales],['products','box',t.products],['finance','wallet',t.finance],['more','more',t.more]] as Array<[Tab, Parameters<typeof Icon>[0]['name'], string]>).map(([id, icon, label]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}><Icon name={icon}/><span>{label}</span></button>)}</nav>

  {modal === "product" && <ProductSheet product={editing} canDelete={canDelete} onClose={() => setModal(null)} onSave={async (values) => { const ok = editing ? await mutate(() => api.updateProduct({ token, shopId: state.activeShopId, id: editing.id, ...values }), "Produit modifié") : await mutate(() => api.addProduct({ token, shopId: state.activeShopId, ...values }), "Produit ajouté"); if (ok) setModal(null); }} onDelete={editing && canDelete ? async () => { const ok = await mutate(() => api.deleteProduct({ token, shopId: state.activeShopId, id: editing.id }), "Produit supprimé"); if (ok) setModal(null); } : undefined}/>} 
  {modal === "expense" && <SimpleFormSheet title="Nouvelle dépense" fields={[{ name: "label", label: "Libellé", required: true }, { name: "amount", label: "Montant (BIF)", type: "number", required: true }, { name: "note", label: "Note (facultatif)" }]} onClose={() => setModal(null)} onSubmit={async (data) => { const ok = await mutate(() => api.addExpense({ token, shopId: state.activeShopId, label: String(data.get("label")), amount: Number(data.get("amount")), note: String(data.get("note") ?? "") || undefined }), "Dépense enregistrée"); if (ok) setModal(null); }}/>} 
  {modal === "shop" && <SimpleFormSheet title="Nouvelle boutique" fields={[{ name: "name", label: "Nom de la boutique", required: true }]} extra={<label className="check"><input type="checkbox" name="demo"/><span>Ajouter les produits de démonstration</span></label>} onClose={() => setModal(null)} onSubmit={async (data) => { const ok = await mutate(() => api.createShop({ token, name: String(data.get("name")), includeDemo: data.get("demo") === "on" }), "Boutique créée"); if (ok) { setModal(null); selectShop(ok.id); } }}/>} 
  {modal === "member" && <SimpleFormSheet title="Ajouter un membre" fields={[{ name: "name", label: "Nom", required: true }, { name: "email", label: "E-mail", type: "email", required: true }, { name: "password", label: "Mot de passe initial (6 caractères min.)", type: "password", required: true }, { name: "role", label: "Rôle", type: "select", options: [["manager","Gérant"],["cashier","Caissier"]], required: true }]} onClose={() => setModal(null)} onSubmit={async (data) => { const roleValue = String(data.get("role")); const ok = await mutate(() => api.addTeamMember({ token, shopId: state.activeShopId, name: String(data.get("name")), email: String(data.get("email")), password: String(data.get("password")), role: roleValue === "manager" ? "manager" : "cashier" }), "Membre ajouté"); if (ok) setModal(null); }}/>} 
  {receipt && <ReceiptSheet sale={receipt} shopName={activeShop?.name ?? "Boutique"} onClose={() => setReceipt(null)} onShare={() => void shareReceipt(receipt)}/>} {toast && <div className="toast" role="status">{toast}</div>}</div>;
}

function DebtRow({ debt, canManage, onPay }: { debt: Debt; canManage: boolean; onPay: (amount: number) => void }) {
  const [open, setOpen] = useState(false); const [amount, setAmount] = useState("");
  return <div className={`debt-row ${debt.status}`}><button onClick={() => setOpen(!open)}><span><b>{debt.customerName}</b><small>{debt.status === "paid" ? "Soldée" : `${debt.payments.length} paiement${debt.payments.length !== 1 ? "s" : ""}`}</small></span><strong>{formatMoney(debt.balance)}</strong></button>{open && <div className="debt-detail"><span>Dette initiale : {formatMoney(debt.originalAmount)}</span>{canManage && debt.balance > 0 && <div><input aria-label={`Paiement de ${debt.customerName}`} type="number" min="1" max={debt.balance} value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Montant"/><button className="secondary" onClick={() => { const value = Number(amount); if (value > 0) { onPay(value); setAmount(""); } }}>Enregistrer le paiement</button></div>}</div>}</div>;
}

function ProductSheet({ product, canDelete, onClose, onSave, onDelete }: { product: Product | null; canDelete: boolean; onClose: () => void; onSave: (value: { name: string; purchasePrice: number; salePrice: number; stock: number; lowStockThreshold: number }) => Promise<void>; onDelete?: () => Promise<void> }) {
  const [busy, setBusy] = useState(false); const margin = product ? product.salePrice - product.purchasePrice : 0;
  return <Sheet title={product ? "Modifier le produit" : "Nouveau produit"} onClose={onClose}><form className="stack-form" onSubmit={(e) => { e.preventDefault(); const data = new FormData(e.currentTarget); setBusy(true); void onSave({ name: String(data.get("name")), purchasePrice: Number(data.get("purchase")), salePrice: Number(data.get("sale")), stock: Number(data.get("stock")), lowStockThreshold: Number(data.get("threshold")) }).finally(() => setBusy(false)); }}><Field label="Nom du produit"><input name="name" required defaultValue={product?.name}/></Field><div className="field-grid"><Field label="Prix d’achat (BIF)"><input name="purchase" type="number" min="0" required defaultValue={product?.purchasePrice}/></Field><Field label="Prix de vente (BIF)"><input name="sale" type="number" min="0" required defaultValue={product?.salePrice}/></Field></div>{product && <p className="margin-note">Marge actuelle : <b>{formatMoney(margin)}</b></p>}<div className="field-grid"><Field label="Quantité en stock"><input name="stock" type="number" min="0" required defaultValue={product?.stock ?? 0}/></Field><Field label="Alerte sous"><input name="threshold" type="number" min="0" required defaultValue={product?.lowStockThreshold ?? 5}/></Field></div><button className="primary" disabled={busy}>{busy ? "Enregistrement…" : "Enregistrer le produit"}</button>{product && canDelete && onDelete && <button type="button" className="danger-text full" onClick={() => void onDelete()}>Supprimer ce produit</button>}</form></Sheet>;
}

type SimpleField = { name: string; label: string; type?: string; required?: boolean; options?: Array<[string, string]> };
function SimpleFormSheet({ title, fields, extra, onClose, onSubmit }: { title: string; fields: SimpleField[]; extra?: ReactNode; onClose: () => void; onSubmit: (data: FormData) => Promise<void> }) {
  const [busy, setBusy] = useState(false); return <Sheet title={title} onClose={onClose}><form className="stack-form" onSubmit={(e) => { e.preventDefault(); setBusy(true); void onSubmit(new FormData(e.currentTarget)).finally(() => setBusy(false)); }}>{fields.map((f) => <Field label={f.label} key={f.name}>{f.type === "select" ? <select name={f.name} required={f.required}>{f.options?.map(([v,l]) => <option value={v} key={v}>{l}</option>)}</select> : <input name={f.name} type={f.type ?? "text"} required={f.required} min={f.type === "number" ? 1 : undefined} minLength={f.type === "password" ? 6 : undefined}/>}</Field>)}{extra}<button className="primary" disabled={busy}>{busy ? "Enregistrement…" : "Enregistrer"}</button></form></Sheet>;
}

function ReceiptSheet({ sale, shopName, onClose, onShare }: { sale: Sale; shopName: string; onClose: () => void; onShare: () => void }) {
  return <Sheet title={`Reçu N° ${sale.id}`} onClose={onClose}><div className="receipt"><div className="receipt-shop"><strong>{shopName}</strong><span>{dateTime(sale.createdAt)}</span></div>{sale.items.map((item) => <div className="receipt-line" key={item.id}><span>{item.quantity} × {item.productName}</span><b>{formatMoney(item.quantity * item.unitPrice)}</b></div>)}<div className="receipt-total"><span>Total</span><strong>{formatMoney(sale.total)}</strong></div><div className="receipt-meta"><span>Paiement</span><b>{sale.paymentMethod}</b></div>{sale.customerName && <div className="receipt-meta"><span>Client</span><b>{sale.customerName}</b></div>}<button className="primary" onClick={onShare}>Partager ou télécharger le reçu</button></div></Sheet>;
}
